services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgres-hub
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data