spring:
  profiles:
    include: private
  application:
    name: ORDER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 19096

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/