spring:
    profiles:
        include: private
    application:
        name: message
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

server:
    port: 19099

eureka:
    client:
        service-url:
            defaultZone: http://localhost:19090/eureka/