version: '3.8'

services:
  postgres:
    image: postgres:15.8
    restart: always
    volumes:
      - db_ai:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  db_ai:
