name: Java CI with Gradle (Message Server)

on:
  pull_request:
    branches:
      - "dev"
    paths:
      - 'client/message/**'

defaults:
  run:
    working-directory: client/message

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Permission
        run: chmod +x ./gradlew

      - name: Run build in a subdirectory
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: client/message
          arguments: 'build'

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: 'client/message/build/test-results/test/TEST-*.xml'